In [1]:
import numpy as np


In [2]:
H = np.asarray([[0.65,0.70,0.29],[0.07,0.99,0.11],[0.27,0.57,0.78]])

In [3]:
H


array([[0.65, 0.7 , 0.29],
       [0.07, 0.99, 0.11],
       [0.27, 0.57, 0.78]])

In [9]:
print(H.T)

[[0.65 0.07 0.27]
 [0.7  0.99 0.57]
 [0.29 0.11 0.78]]


In [11]:
D = np.linalg.matrix_power(H.T, -1)

In [12]:
print(D)

[[ 1.87798274 -0.06590806 -0.60190736]
 [-1.00767869  1.13473037 -0.48041419]
 [-0.55611582 -0.1355218   1.57358807]]
